### ISSUE TITLE
Charlie Daly

### ISSUE THREAD

**Issue by mistakenot** [WorldBrain/TEAM#21]
### Hi! My name is...

_Charlie Daly._
### Hi! My (**GitHub nick**)name is...

@mistakenot
### You can reach me here...

_Here or the_charlie_daly@hotmail.co.uk_
### This is the city and time zone I am mostly in...

_UK_
### I am currently available...
- [ ] Not until mm/dd/yyyy and then...
- [x] 1-3 hour(s) per **Week**
- [ ] ___ hour(s) per **Month**
- [ ] irregular, only on request
- [ ] other: 
### I consider it to fun to...

_Lick windows and shout at computers. Not always in that order._
### I want to contribute to WorldBrain because...

_Want to learn how to contribute to OSS on a project that aims to do good._
### I regularly use these languages and frameworks:

| Languages/Frameworks/Technologies | Level (1=apprentice to 5=wizard) |
| --- | --- |
| C# / ASP.NET | 4 |
| Javascript / Node JS | 3 |
| Scala, Play Framework, Akka | 3 |
| Ruby / Rails | 1 |
| Python | 1 |
### In the next year, I want to learn...

_How to contribute to open source software; not contributed anything serious to a Github project yet. Happy to improve skills on specific tech as well e.g. Python._

**Comment by oliversauter** [comment]
Hey Charlie! @mistakenot 
Nice to welcome you here.
Hope you had a nice trip back home. 
Looking forward working with you!

**Comment by mistakenot** [comment]
Hi @oliversauter, flight back was fine :) Looking forward to seeing where the project goes.
