### ISSUE TITLE
TEAM: DataScience

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/TEAM#24]
## GOAL OF TEAM

The goal of this team is to build and constantly improve the search and recommendation function and implement these upgrades.
## How to get involved:
1. Introduce yourself to [this team's gitter chat](https://gitter.im/WorldBrain/TEAM_crawler)  
2. Check [out our open tasks](https://github.com/WorldBrain/cortex/issues?q=is%3Aissue+is%3Aopen+label%3A%22TEAM%3A+DataScience%22).
## Contributors in this team:

[Meet the people](https://github.com/WorldBrain/TEAM/issues?q=is%3Aissue+is%3Aopen+label%3A%22TEAM%3A+DataScience%22) working on this.

**Comment by oliversauter** [comment]
I join here.
You find more about me in the member issue #1  

Here I can help by understanding the technical concept and with ideas on how to improve search/recommendation from our users point of view.

**Comment by e911miri** [comment]
I join here too

You can find out about me #3 

Here I can help with the development of the search engine, I prefer python but I am open to learn and use any other stack, please include me in any calls

**Comment by arsenal9971** [comment]
I join here too, 

 I have good expierience with data science in general, as well as with machine learning and other statistical models, I can program in python if it is the common language, for code review purposes and stuff, but I also would like to code some in Julia. 

You can get more info about me #10

**Comment by zarco** [comment]
Joining here...
I have some basic experience with ML in Spark. Currently taking the Data Science specialization on Coursera, so I can do R code, but also like Python and Scala.
In my current job I'm working with Cassandra, TitanDB and Time series models
more about me --> #22
