### ISSUE TITLE
Tomiwa Ijaware

### ISSUE THREAD

**Issue by e911miri** [WorldBrain/TEAM#3]
### Name:

_Tomiwa Ijaware_
### GitHub nick:

_@e911miri_
### Which time zone(s) are you mostly in?

_Lagos/GMT+1_
### Who are you?

_I am completely fascinated by people's personalities, in my spare time, I am looking for new theories that help understand why we act/think the way we do_
### Why am I contributing to WorldBrain?

_I have a knack for finding patterns that no one sees, for creating structure out of chaos. I am an advocate of using the design process in building software and I want to create tools that get smarter with use._
### Which technologies do I use regularly (languages, frameworks)?

| Languages/Frameworks/Technologies | Level (1=apprentice to 5=wizard) |
| --- | --- |
| Python | 3 |
| Flask | 3 |
| Sci-kit learn | 1 |
### What do I want to learn in the next year(s)?

_I want to have mastered machine learning techniques using real life scenarios_

**Comment by oliversauter** [comment]
Hello Tomiwa:) 

Nice hear from you! Thanks for that random join:) happy to see that!

Would love to get to know you, how about we have a skype call somewhat in the coming days?

Just ping me under oli@worldbrain.io

Welcome to WorldBrain:)
Oliver

**Comment by e911miri** [comment]
Hi Oliver,

Thanks for the warm welcome :)

We can have a skype call anytime, my skype id is **e911miri**

Cheers!!
Tomiwa

**Comment by oliversauter** [comment]
Ok :)

I added you on skype. Let's chat there about a time regarding skyping!

**Comment by e911miri** [comment]
Nice,

Can we chat later tonight or early tomorrow morning? I just need 30mins -
1hr notice ahead

**Comment by oliversauter** [comment]
Sorry, for not responding earlier.

How about Sunday evening 6pm or later ?

**Comment by e911miri** [comment]
It's okay,

Sunday evening works perfect for me
