### ISSUE TITLE
Fuad Mohamoud

### ISSUE THREAD

**Issue by ProgrammingFuad** [WorldBrain/TEAM#40]
### Hi! My name is...
Fuad Mohamoud
_your name - Please name the issue the same way_

### Hi! My (**GitHub nick**)name is...
@ProgrammingFuad

### You can reach me here...

fuad.mohamoud@und.edu
or on Open Minded Innovations Slack channel!

### This is the city and time zone I am mostly in...
The North American Central Time Zone (CT)
I live in Saint Paul, Minnesota

### I am currently available...

 - [ ]  15 hour(s) per **Week**

### I consider it to fun to...

Make stuff that seems cool to me. 
Got tired of viewing the requirements for programming assinments in a TXT file my professor would send out. So built a File Converter in Java to make them into nice looking webpages. 

Everyone wants my source file now. ( I've given it to everyone whose offered me candy :D )

### I want to contribute to WorldBrain because...

What excites me about this project is the limitlessness of the project. So many things could be done to improve it, and all in cool ways.

### I regularly use these languages and frameworks:

| Languages/Frameworks/Technologies  | Level (1=apprentice to 5=wizard)  |

Java                         3
JavaScript                1
BootStrap                3
Python                     1

### In the next year, I want to learn...

JavaScript and Machine Learning

_Any languages, frameworks or techniques you want to learn and where we can help you?_

Want to learn JavaScript. Also get my hands dirty with ReactJS and Machine Learning/ Deep Learning

**Comment by oliversauter** [comment]
Hey Muhamoud!

Great to hear from you. :) 
Will send you an email later, would be nice to have a skype chat in the coming days to get to know each other!
