### ISSUE TITLE
Bruno Medina

### ISSUE THREAD

**Issue by brusMX** [WorldBrain/TEAM#6]
### Hi! My name is...

_Bruno Medina_
### Hi! My (**GitHub nick**)name is...

_@brusMX_
### This is the city and time zone I am mostly in...

_America/Mexico_City_ (Usually UTC-06:00, but then again we have DST)
### I am currently available...
- Not until 04/23/2016 and then...
- 12 hour(s) per **Week**
### I consider it to fun to...
- Snowboard
- Go to meet ups
- Discuss philosophy
- Drink a beer in a jacuzzi while a deer is staring at me in a threatening pose
### I am contributing to WorldBrain because...
- I'm tired of fake advertising trying to fool people with esoteric and non-existent "studies"
- Education is the only hope the humanity has to prevail
### I regularly use these languages and frameworks:

| Languages/Frameworks/Technologies | Level (1=apprentice to 5=wizard) |
| --- | --- |
| PHP | 4 |
| JS | 3.5 |
| C# | 3 |
| Ruby | 3 |
| Objective-C | 3 |
### In the next year, I want to learn...

_More about making distributable and highly efficient recognition algorithms_

**Comment by oliversauter** [comment]
> Education is the only hope the humanity has to prevail

Word :)
