### ISSUE TITLE
Facundo Sa

### ISSUE THREAD

**Issue by Facusa7** [WorldBrain/TEAM#8]
### Hi! My name is...

Facundo Sa
### Hi! My **GitHub nick** name is...

@facusa7
### You can reach me here...

Email: sajuanfacundo@gmail.com / facusa7@hotmail.com
Skype name: facundo.sa
### This is the city and time zone I am mostly in...

Buenos Aires, Argentina / Time Zone: UTC-3:00
### I am currently available...
- [ ] Not until 04/17/2016 and then...
- [ ] 6 hour(s) per **Week**
- [ ] 30 hour(s) per **Month**
### I consider it to fun to...

Play guitar, walk a lot, sing alone and watch TV series. 
### I am contributing to WorldBrain because...

_I am contributing because I want be part of a real open source project to produce a software that could be very useful for so many people. I'm very excited because it is the first time that I will contribute to a project that can be very succesfull. I feel that is the best oportunity to improve my skills and to build my future in this field._
### I regularly use these languages and frameworks:

| Languages/Frameworks/Technologies | Level (1=apprentice to 5=wizard) |
| --- | --- |
| Javascript/ Jquery | 4 |
| C# / ASP.NET / VisualStudio | 3 |
| Python / Django | 3 |
| PHP / CakePhp | 3 |
| Knockout JS | 2 |
### In the next year, I want to learn...

I want to learn more JS Frameworks. I know a few, I think it is very important to build javascript code in a proper way.

**Comment by oliversauter** [comment]
Hey Facundo!
For your interest in learning more JS frameworks. Have you looked into https://www.meteor.com/ yet?

**Comment by lwm** [comment]
@Facusa7 You have some spare time? We are bootstrapping our django project now and need some help :)

**Comment by Facusa7** [comment]
I will be happy to help!
